import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: {
    default: "CBLUE - Thailand's #1 AI Home Services & Real Estate Platform | แพลตฟอร์มช่างซ่อมบำรุงและอสังหาริมทรัพย์อันดับ 1",
    template: "%s | CBLUE",
  },
  description:
    "CBLUE connects you with verified fixers, project teams, professionals & property listings across Thailand. AI-powered matching for plumbing, electrical, AC, smart home, architecture, legal services, and real estate. จองช่างซ่อมบ้าน ทีมโครงการ มืออาชีพ และอสังหาริมทรัพย์ทั่วไทย",
  keywords: [
    "会计师",
    "二手仓库",
    "ทาวน์เฮ้าส์ให้เช่า",
    "房屋出售",
    "Safety manager search",
    "Construction Electrical Engineer",
    "Rent factory",
    "หาผู้ตรวจสอบบัญชี",
    "二手房",
    "เช่าอาคาร",
    "Software Programer",
    "Rent building",
    "หาวิศวกรไฟฟ้าควบคุมงาน",
    "Site engineer",
    "Designer",
    "ขายบ้าน",
    "出售联排别墅",
    "เช่าออฟฟิศ",
    "Factory for rent",
    "二手公寓",
    "Sell townhouse",
    "หาโปรแกรมเมอร์",
    "找施工机械工程师",
    "找消防生命安全",
    "หาทนายความ",
    "租建筑",
    "House",
    "建筑师",
    "ขายโรงงาน",
    "找数字营销",
    "อาคารมื่อสอง",
    "健康安全环境经理",
    "土地",
    "ผู้สอบบัญชีรับอนุญาต",
    "หาวิศวกรโยธาออกแบบ",
    "Safety officer",
    "数字营销",
    "土地出售",
    "安全员",
    "Second-hand condo",
    "หาวิศวกรโยธาควบคุมงาน",
    "设计机械工程师",
    "คอนโดมื่อสอง",
    "ขายคอนโด",
    "Buy townhouse",
    "找设计机械工程师",
    "Land for sale",
    "ตรวจประจำปี",
    "建筑出租",
    "Factory for sale",
    "Design Civil Engineer",
    "Find designer",
    "HSE manager search",
    "公寓出售",
    "เจ้าหน้าที่ความปลอดภัย",
    "House for sale",
    "找律师",
    "การตลาดดิจิทัล",
    "Professional",
    "หาวิศวกรไฟฟ้าออกแบบ",
    "找会计师",
    "บ้านให้เช่า",
    "หา FLS",
    "二手建筑",
    "找审计师",
    "找健康安全环境经理",
    "หาวิศวกรเครื่องกลควบคุมงาน",
    "Annual inspection",
    "Rent condo",
    "设计师",
    "二手工厂",
    "ผู้จัดการความปลอดภัย",
    "Find safety officer",
    "firelifesafety search",
    "工厂出租",
    "施工机械工程师",
    "找设计电气工程师",
    "Factory",
    "Interior Designer",
    "Condo for sale",
    "找安全员",
    "租土地",
    "ทนายความ",
    "เช่าโรงงาน",
    "Land for rent",
    "CPA search",
    "找专业人士",
    "租房",
    "专业人士",
    "Find site engineer",
    "หาผู้จัดการความปลอดภัย",
    "找设计土木工程师",
    "找安全经理",
    "找FLS",
    "房屋出租",
    "Land",
    "มืออาชีพ",
    "ที่ดิน",
    "租公寓",
    "Safety manager",
    "สถาปนิก",
    "เช่าบ้าน",
    "联排别墅出租",
    "วิศวกรโยธาควบคุมงาน",
    "仓库出租",
    "找软件程序员",
    "Construction Mechanical Engineer",
    "Digital Marketing",
    "ทาวน์เฮ้าส์มื่อสอง",
    "找联排别墅",
    "Design Civil Engineer search",
    "หาวิศวกรเครื่องกลออกแบบ",
    "仓库出售",
    "บ้าน",
    "Construction Civil Engineer",
    "找施工土木工程师",
    "找注册会计师",
    "บ้านมื่อสอง",
    "ขายทาวน์เฮ้าส์",
    "二手土地",
    "Warehouse for rent",
    "Second-hand townhouse",
    "Digital Marketing search",
    "仓库",
    "租工厂",
    "เช่าโกดัง",
    "设计土木工程师",
    "施工电气工程师",
    "CPA",
    "หาการตลาดดิจิทัล",
    "โรงงานมื่อสอง",
    "Find home repairman",
    "Warehouse",
    "Building",
    "วิศวกรไฟฟ้าออกแบบ",
    "Rent office",
    "หามัณฑนากร",
    "อาคาร",
    "ขายที่ดิน",
    "土地出租",
    "年度检查",
    "Rent house",
    "Rent land",
    "租仓库",
    "firelifesafety",
    "Second-hand warehouse",
    "มัณฑนากร",
    "คอนโด",
    "Lawyer",
    "FLS search",
    "หาผู้สอบบัญชีรับอนุญาต",
    "软件程序员",
    "ผู้จัดการอาชีวอนามัย",
    "ผู้ออกแบบ",
    "เช่าที่ดิน",
    "โกดังมื่อสอง",
    "คอนโดให้เช่า",
    "วิศวกรเครื่องกลออกแบบ",
    "อาคารให้เช่า",
    "Design Mechanical Engineer",
    "注册会计师",
    "Interior Designer search",
    "Auditor",
    "Home repairman",
    "Rent warehouse",
    "House for rent",
    "消防生命安全",
    "设计电气工程师",
    "安全经理",
    "找建筑师",
    "accountant",
    "ที่ดินให้เช่า",
    "Townhouse for rent",
    "accountant search",
    "工厂",
    "Architect",
    "现场工程师",
    "找室内设计师",
    "วิศวกรโยธาออกแบบ",
    "找房屋维修工",
    "วิศวกรไฟฟ้าควบคุมงาน",
    "Condo",
    "ความปลอดภัยด้านอัคคีภัย",
    "หาเจ้าหน้าที่ความปลอดภัย",
    "Second-hand building",
    "建筑出售",
    "Architect search",
    "租办公室",
    "หาความปลอดภัยด้านอัคคีภัย",
    "Construction Civil Engineer search",
    "购买联排别墅",
    "วิศวกรกรควบคุมงาน",
    "ขายอาคาร",
    "โรงงานให้เช่า",
    "Lawyer search",
    "施工土木工程师",
    "หาสถาปนิก",
    "Find townhouse",
    "โกดัง",
    "Find auditor",
    "ออฟฟิศ",
    "นักบัญชี",
    "หาทาวน์เฮ้าส์",
    "Building for rent",
    "审计师",
    "室内设计师",
    "Second-hand land",
    "建筑",
    "律师",
    "找设计师",
    "โกดังให้เช่า",
    "房屋",
    "二手联排别墅",
    "找现场工程师",
    "Find professional",
    "Design Electrical Engineer",
    "找施工电气工程师",
    "ผู้ตรวจสอบบัญชี",
    "หาวิศวกรกรควบคุมงาน",
    "ขายโกดัง",
    "工厂出售",
    "หาผู้จัดการอาชีวอนามัย",
    "โรงงาน",
    "Office",
    "Second-hand factory",
    "ซื้อทาวน์เฮ้าส์",
    "Warehouse for sale",
    "FLS",
    "หาช่างซ่อมบ้าน",
    "หามืออาชีพ",
    "หานักบัญชี",
    "HSE manager",
    "Building for sale",
    "หาผู้ออกแบบ",
    "房屋维修工",
    "公寓出租",
    "วิศวกรเครื่องกลควบคุมงาน",
    "ที่ดินมื่อสอง",
    "办公室",
    "เช่าคอนโด",
    "Condo for rent",
    "Second-hand house",
    "公寓",
    "โปรแกรมเมอร์",
    "ช่างซ่อมบ้าน",
    // Existing keywords below

    // Brand
    "CBLUE", "cblue.co.th", "cblue.th", "Cblue Thailand", "CBLUE platform",
    // Home services
    "Thailand home services", "find fixer Thailand", "book plumber Bangkok",
    "hire electrician Thailand", "air conditioning repair Thailand", "home maintenance Thailand",
    "smart home installation", "handyman Bangkok", "home repair service Thailand",
    // Project teams
    "project team Thailand", "hire architect Thailand", "construction management Thailand",
    "interior designer Bangkok", "civil engineer Thailand", "mechanical engineer Thailand",
    "electrical engineer Thailand",
    // Professionals
    "lawyer Thailand", "accountant Bangkok", "CPA Thailand", "safety officer Thailand",
    "digital marketing Thailand", "software programmer Thailand",
    // Real estate
    "property listing Thailand", "real estate Thailand", "condo for sale Bangkok",
    "house for rent Thailand", "land for sale Thailand", "property management Thailand",
    "warehouse for rent Thailand", "commercial space Bangkok", "apartment for rent Bangkok",
    "townhouse for sale Bangkok", "villa for rent Phuket",
    // AI & tech
    "AI matching platform", "PromptPay payment", "enterprise service marketplace",
    "AI chatbot development", "machine learning Thailand", "AI integration services",
    "software development Thailand", "mobile app development Thailand",
    // Green building & sustainability (from cblue-ai)
    "green building Thailand", "green building design", "sustainable building", "LEED certification Thailand",
    "green architecture", "eco-friendly building", "net zero building Thailand",
    "carbon neutral construction", "green infrastructure", "sustainable cities Thailand",
    "green roof Thailand", "vertical garden Bangkok",
    // Solar & EV (from cblue-ai)
    "solar panel installation Thailand", "solar solutions Thailand", "EV charging station Thailand",
    "EV charger installation", "renewable energy Thailand", "solar energy Thailand",
    // Smart tech (from cblue-ai)
    "smart home automation Thailand", "building automation system", "BAS Thailand", "BMS Thailand",
    "smart building controls", "IoT building Thailand", "smart thermostat Thailand",
    "smart farming Thailand", "IoT agriculture Thailand",
    // HVAC & construction (from cblue-ai)
    "HVAC MEP retrofit", "kitchen renovation Thailand", "fit-out contractor Bangkok",
    "reinstatement contractor", "general construction management", "modular housing Thailand",
    // Security (from cblue-ai)
    "security CCTV installation", "door access control", "biometric access control Thailand",
    "environmental services Thailand", "green construction Thailand",
    // Thai keywords
    "ช่างซ่อมบ้าน", "จองช่าง", "ซ่อมประปา", "ซ่อมไฟฟ้า", "ซ่อมแอร์", "ช่างแอร์",
    "หาช่าง", "บริการซ่อมบ้าน", "ช่างประปา", "ช่างไฟฟ้า", "หาช่างซ่อม",
    "ทีมโครงการ", "สถาปนิก", "ทนายความ", "วิศวกร", "ออกแบบภายใน", "มัณฑนากร",
    "นักบัญชี", "ผู้สอบบัญชี", "โปรแกรมเมอร์", "การตลาดดิจิทัล",
    "วิศวกรไฟฟ้า", "วิศวกรเครื่องกล", "วิศวกรโยธา", "เจ้าหน้าที่ความปลอดภัย",
    "อสังหาริมทรัพย์", "คอนโดขาย", "บ้านเช่า", "ที่ดินขาย", "บ้านมือสอง",
    "คอนโดให้เช่า กรุงเทพ", "บ้านขาย กรุงเทพ", "อาคารพาณิชย์", "โกดังให้เช่า",
    "สมาร์ทโฮม", "พลังงานแสงอาทิตย์", "EV charging", "โซลาร์เซลล์",
    "อาคารเขียว", "ก่อสร้างเขียว", "ระบบอาคารอัจฉริยะ", "เกษตรอัจฉริยะ",
    "แพลตฟอร์ม AI", "จับคู่ช่าง", "บริการซ่อมบำรุง", "จองช่างออนไลน์",
    "พลังงานหมุนเวียน", "อาคารประหยัดพลังงาน", "ระบบรักษาความปลอดภัย",
    "ระบบ CCTV", "ระบบควบคุมอาคาร", "สวนแนวตั้ง", "บ้านอัจฉริยะ",
    // Chinese keywords
    "泰国家政服务", "找维修师傅", "曼谷维修", "泰国房地产", "AI匹配平台",
    "泰国绿色建筑", "泰国智能家居", "曼谷公寓出售", "泰国别墅出租",
    "太阳能安装泰国", "电动汽车充电站", "楼宇自动化系统", "智慧农业泰国",
    "泰国律师", "泰国会计师", "泰国建筑师", "软件开发泰国", "AI聊天机器人",
    "可持续建筑", "零碳建筑", "绿色建筑设计", "智能家居自动化",
  ],
  metadataBase: new URL("https://www.cblue.co.th"),
  alternates: {
    canonical: "/",
    languages: { "th": "/th", "en": "/en", "zh": "/zh" },
  },
  openGraph: {
    type: "website",
    locale: "th_TH",
    alternateLocale: ["en_US", "zh_CN"],
    siteName: "CBLUE",
    title: "CBLUE - Thailand's #1 AI Home Services & Real Estate Platform",
    description: "AI-powered matching for fixers, project teams, professionals & properties across Thailand. Book trusted services with PromptPay payment.",
    url: "https://www.cblue.co.th",
    images: [{ url: "/images/scenic-building.jpg", width: 1200, height: 630, alt: "CBLUE Platform" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "CBLUE - Thailand's #1 AI Home Services Platform",
    description: "Find verified fixers, architects, lawyers & properties. AI matching + PromptPay.",
    images: ["/images/scenic-building.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 },
  },
  icons: {
    icon: [
      { url: "/favicon.ico", type: "image/x-icon" },
      { url: "/images/favicon-c.png", type: "image/png", sizes: "512x512" }
    ],
    apple: [
      { url: "/images/favicon-c.png", sizes: "180x180", type: "image/png" }
    ],
    shortcut: [ { url: "/favicon.ico" } ]
  },
  other: {
    "msvalidate.01": "",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
    "apple-mobile-web-app-title": "CBLUE",
    "format-detection": "telephone=no",
    "mobile-web-app-capable": "yes",
    "theme-color": "#0284c7",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <meta name="theme-color" content="#0284c7" />
        <link rel="preconnect" href="https://www.cblue.co.th" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" href="/images/favicon-c.png" type="image/png" />
        <link rel="apple-touch-icon" href="/images/favicon-c.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Organization schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "CBLUE",
              url: "https://www.cblue.co.th",
              logo: "https://www.cblue.co.th/images/logo.jpg",
              description: "Thailand's #1 AI-powered platform for home services, project teams, professionals, and real estate. แพลตฟอร์มช่างซ่อมบ้าน ทีมโครงการ มืออาชีพ และอสังหาริมทรัพย์. 泰国第一AI家居服务与房地产平台",
              address: { "@type": "PostalAddress", addressCountry: "TH" },
              sameAs: [],
              areaServed: { "@type": "Country", name: "Thailand" },
              serviceType: [
                "Home Maintenance", "Plumbing", "Electrical", "Air Conditioning",
                "Interior Design", "Landscaping", "Cladding & Roofing",
                "Project Management", "Green Building Design", "HVAC MEP & Retrofit",
                "Smart Building Automation", "Solar Panel Installation", "EV Charging",
                "Kitchen Renovation", "Fit-out", "Reinstatement",
                "Professional Services", "Architecture", "Legal Services", "Engineering",
                "Accounting", "Digital Marketing", "Software Development",
                "Real Estate", "Property Listing", "Property Management",
                "Smart Home", "Smart Farming", "Environmental Services", "Security & CCTV",
              ],
            }),
          }}
        />
        {/* WebSite schema with SearchAction for Google/Bing sitelinks search */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "CBLUE",
              alternateName: ["cblue.co.th", "ช่างซ่อมบ้าน CBLUE", "CBLUE泰国"],
              url: "https://www.cblue.co.th",
              inLanguage: ["th", "en", "zh"],
              potentialAction: {
                "@type": "SearchAction",
                target: {
                  "@type": "EntryPoint",
                  urlTemplate: "https://www.cblue.co.th/th/services?q={search_term_string}",
                },
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
        {/* LocalBusiness schema for Google Maps / local SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              "@id": "https://www.cblue.co.th/#business",
              name: "CBLUE Thailand",
              image: "https://www.cblue.co.th/images/logo.jpg",
              url: "https://www.cblue.co.th",
              telephone: "",
              address: {
                "@type": "PostalAddress",
                addressLocality: "Bangkok",
                addressRegion: "Bangkok",
                addressCountry: "TH",
              },
              geo: {
                "@type": "GeoCoordinates",
                latitude: 13.7563,
                longitude: 100.5018,
              },
              priceRange: "฿100 - ฿1000",
              openingHoursSpecification: {
                "@type": "OpeningHoursSpecification",
                dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
                opens: "00:00",
                closes: "23:59",
              },
              areaServed: {
                "@type": "Country",
                name: "Thailand",
              },
            }),
          }}
        />
        {children}
      </body>
    </html>
  );
}
